<ExpansionContent>:
    adaptive_height: True

    MDBoxLayout:
        adaptive_height: True
        orientation: "horizontal"
        padding: [dp(40), dp(5)]

        MDTextField:
            hint_text: "Írd be a keresett termék nevét"
            pos_hint: {'center_x': 0.5, 'center_y': 0.5}
            size_hint_x: None
            width: "280dp"
            on_text_validate: app.perform_search(self.text)