<ForgottenPwContent>:
    spacing: "20dp"
    size_hint_y: None
    text: forgotten_pw_email.text
    height: "120dp"

    MDTextField:
        id: forgotten_pw_email
        pos_hint: {'center_x': 0.5}
        pos_hint: {'center_y': 0.5}
        size_hint: None, None
        width: "300dp"
        hint_text: "Add meg az e-mail címed"
        helper_text: "Erre az e-mail címre fogunk küldeni egy e-mailt"
        helper_text_mode: "on_focus"