#:include kivy_lang/login_screen.kv
#:include kivy_lang/register_screen.kv
#:include kivy_lang/navigation_screen.kv
#:include kivy_lang/shop_card.kv
#:include kivy_lang/forgotten_pw_content.kv
#:include kivy_lang/show_hide_pw_icon.kv
#:include kivy_lang/dialog_content.kv
#:include kivy_lang/list_item_with_checkbox.kv
#:include kivy_lang/expansion_content.kv
#:import screens screens
#:import components components

WindowManager:
    LoginScreen:
    RegisterScreen:
    NavigationScreen: